const GET_ClASSIFY = "GET_ClASSIFY";
const GET_SPECIAL = "GET_SPECIAL ";
const GET_ACCOUNT = "GET_ACCOUNT ";
const GET_ALL = "GET_ALL";
const GET_RECOMMEND = "GET_RECOMMEND";
const GET_SHOPPING = "GET_SHOPPING";
const GET_USER = "GET_USER";
const GET_BANNERS = "GET_BANNERS";
const GET_MOUTH = "GET_MOUTH";
const GET_RANGE = "GET_RANGE";
export {GET_RANGE,GET_MOUTH,GET_ClASSIFY,GET_SPECIAL,GET_ACCOUNT,GET_ALL,GET_RECOMMEND,GET_SHOPPING,GET_USER,GET_BANNERS}