const CHANGE_FIND_BANNERS = "CHANGE_FIND_BANNERS"
const CHANGE_FIND_HOTBAN = "CHANGE_FIND_HOTBAN"
const CHANGE_FIND_LIST="CHANGE_FIND_LIST"
const CHANE_FIND_CONTENT="CHANE_FIND_CONTENT"
const CHANE_FIND_CONTENTTWO="CHANE_FIND_CONTENTTWO"
export {
    CHANGE_FIND_BANNERS,
    CHANGE_FIND_HOTBAN,
    CHANGE_FIND_LIST,
    CHANE_FIND_CONTENT,
    CHANE_FIND_CONTENTTWO
}